name: Build & Publish docker

on:
  workflow_dispatch:
    inputs:
      pkg-version:
        type: string
        description: The version of the package
  push:
    branches: ["main"]
    paths:
      - Dockerfile
      - .dockerignore
      - pkg-info.json
  pull_request:
    paths:
      - Dockerfile
      - .dockerignore
      - pkg-info.json
    branches: ["main"]

jobs:
  build:
    uses: FirelightFlagboy/gh-actions-workflows-docker-services/.github/workflows/docker-build-publish.yml@aab594706e19dd4afe38efa7bbc4c3de33dff0b3
    permissions:
      contents: read
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    with:
      docker-username: firelightflagbot
      pkg-version: ${{ inputs.pkg-version || '4.0.0.688' }}
      platforms: linux/amd64,linux/arm64
      registry: docker.io
      tags: firelightflagbot/sonarr:${{ inputs.pkg-version || '4.0.0.688' }}
    secrets:
      docker-password: ${{ secrets.DOCKER_HUB_PAT }}
