name: Update pkg info file

on:
  schedule:
    - cron: 0 5 1 * * # every 1st day of the month
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/pkg-info.yml

jobs:
  update-pkg:
    uses: FirelightFlagboy/gh-actions-workflows-docker-services/.github/workflows/update-pkg-info.yml@25d902f56f1e8b241e3b0fd1502e0c29e90870f6
    permissions:
      contents: write
      pull-requests: write
    with:
      pkg-info-path: pkg-info.json
